#!/usr/bin/env python3
"""Emit conformance/vectors.json as literal C data (generated, not checked
in — see run). Only the fields the engine's host test needs: count_vectors,
valid_rule_ids, invalid_rule_ids, evolution. lifetimes (R-E2) waits for the
boring detector; anything about pairs, scripts, or help text is out of
scope for an engine with no file I/O or CLI.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent


def c_string(s):
    out = ['"']
    for ch in s:
        if ch in ('"', "\\"):
            out.append("\\" + ch)
        elif ch == "\n":
            out.append("\\n")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def main():
    vectors = json.loads((ROOT / "conformance" / "vectors.json").read_text())
    out = []
    out.append("// Generated by platformio/host_test/gen_vectors.py")
    out.append(f"// from conformance/vectors.json, version {vectors['version']!r}.")
    out.append("// Do not edit; do not check in (see .gitignore). Run `./run` to regenerate.")
    out.append("#ifndef VECTORS_DATA_H")
    out.append("#define VECTORS_DATA_H")
    out.append("")

    cv = vectors["count_vectors"]
    out.append(f"static const unsigned char gen_count_vectors[{len(cv)}][4] = {{")
    for row in cv:
        out.append("    {" + ", ".join(str(n) for n in row) + "},")
    out.append("};")
    out.append(f"static const int gen_count_vectors_count = {len(cv)};")
    out.append("")

    for key in ("valid_rule_ids", "invalid_rule_ids"):
        ids = vectors[key]
        out.append(f"static const char *gen_{key}[] = {{")
        for rule_id in ids:
            out.append(f"    {c_string(rule_id)},")
        out.append("};")
        out.append(f"static const int gen_{key}_count = {len(ids)};")
        out.append("")

    evolution = vectors["evolution"]
    for i, case in enumerate(evolution):
        out.append(f"static const char *gen_evolution_{i}_expected[] = {{")
        for row in case["expected"]:
            out.append(f"    {c_string(row)},")
        out.append("};")
    out.append("")
    out.append("typedef struct {")
    out.append("    const char *name;")
    out.append("    const char *rule;")
    out.append("    int wrap;")
    out.append("    const char *initial;")
    out.append("    int generations;")
    out.append("    const char *const *expected;")
    out.append("} gen_evolution_case;")
    out.append("")
    out.append(f"static const gen_evolution_case gen_evolution[{len(evolution)}] = {{")
    for i, case in enumerate(evolution):
        out.append("    {%s, %s, %d, %s, %d, gen_evolution_%d_expected}," % (
            c_string(case["name"]), c_string(case["rule"]),
            1 if case["wrap"] else 0, c_string(case["initial"]),
            case["generations"], i,
        ))
    out.append("};")
    out.append(f"static const int gen_evolution_count = {len(evolution)};")
    out.append("")
    out.append("#endif")
    out.append("")

    dest = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).parent / "build" / "vectors_data.h"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(out))
    print(f"gen_vectors: wrote {dest} ({len(cv)} count vectors, "
          f"{len(vectors['valid_rule_ids'])} valid + {len(vectors['invalid_rule_ids'])} invalid IDs, "
          f"{len(evolution)} evolution cases)")


if __name__ == "__main__":
    main()
